---
# This is the configuration file for the Nanopore cDNA differential expression tutorial.
# The configuration must be specified in YAML format

# indentation is required as in this template - a single indent is 4 spaces


pipeline: "Nanopore cDNA gene expression profiling"

reference_genome: "ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

genome_annotation: "ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz"

Samples:
    - "DMSO":   
        A1: "fastq/DMSO_replicate1.fastq.gz"
        A2: "fastq/DMSO_replicate2.fastq.gz"
        A3: "fastq/DMSO_replicate3.fastq.gz"
        A4: "fastq/DMSO_replicate4.fastq.gz"

    - "BaP_PD153035":
        B1: "fastq/BaP_PD153035_replicate1.fastq.gz"
        B2: "fastq/BaP_PD153035_replicate2.fastq.gz"
        B3: "fastq/BaP_PD153035_replicate3.fastq.gz"
        B4: "fastq/BaP_PD153035_replicate4.fastq.gz"

    - "BaP":
        C1: "fastq/BaP_replicate1.fastq.gz"
        C2: "fastq/BaP_replicate2.fastq.gz"
        C3: "fastq/BaP_replicate3.fastq.gz"
        C4: "fastq/BaP_replicate4.fastq.gz"
        
    - "PCB":
        D1: "fastq/PCB_replicate1.fastq.gz"
        D2: "fastq/PCB_replicate2.fastq.gz"
        D3: "fastq/PCB_replicate3.fastq.gz"
        D4: "fastq/PCB_replicate4.fastq.gz"

referenceGroup: "DMSO"   # this name *must* match one of the group names

readCountMinThreshold: 10   # what is the minimum number of transcripts for a gene feature to be considered
lfcThreshold : 1            # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis

tutorialText: FALSE
# please change the tutorialText: value to FALSE to mask the tutorial instructions
