# Generated by Django 3.2.6 on 2021-08-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duesselpore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='study_group',
            field=models.CharField(default='second group', help_text='Your study group (must be one of your subfolder name)', max_length=100, verbose_name="Study group (study groups's sub-directory name)"),
        ),
    ]
