# Generated by Django 3.2.8 on 2022-02-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duesselpore', '0002_alter_input_study_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='seq_method',
            field=models.CharField(choices=[('nanopore', 'Oxford Nanopore (long read)'), ('pacbio', 'PacBio (long read)'), ('illumina', 'illumina (short read)')], default='nanopore', max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='pathway_ID',
            field=models.CharField(default='hsa04144', max_length=10, verbose_name='KEGG id (for pathview)'),
        ),
        migrations.AlterField(
            model_name='input',
            name='reference_genes',
            field=models.CharField(choices=[('human', 'Human hg38 (Homo sapiens)'), ('mouse', 'Mouse (Mus musculus)'), ('rat', 'Rat (Rattus norvegicus)'), ('zebrafish', 'Zebrafish (Danio rerio)'), ('celegans', 'Caenorhabditis elegans'), ('covid19', 'SARS-CoV-2')], default='human', max_length=100),
        ),
    ]
